a=input("enter 1st number")
b=input("enter 2nd number")
print("Entered no.is",a,b)
print("sum is ",int(a) + int(b))
print("------------------------")
c=int(input("enter 1st number"))
d=int(input("enter 2nd number"))
print("Entered no.is",c,d)
print("sum is ",c+d)