a=[353,82,90,49,58,99]
print(type(a[0]))
print(type(a[1]))
print(type(a[2]))
print("original a value             ===",a)
a.sort()
print("sorted a                     ===",a)
a.reverse()
print("reverse                      ===",a)
a.remove(82)
print("removed 82                   ===",a)
a.append(11)
print("11 appended                  ===",a)
a.insert(2,"77")
print("inserted \"77\" in 3rd posision===",a)
print(type(a[0]))
print(type(a[1]))
print(type(a[2]))
a.pop()
print("pop                          ===",a)
#del(a)
a.clear()
print("clear                        ===",a)
